name: CI/CD Pipeline

on:
  push:
    branches:
      - main # 监听main分支的推送

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Write secrets to backend/.env
        run: |
          echo "R2_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }}" >> backend/.env
          echo "R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }}" >> backend/.env
          echo "R2_BUCKET_NAME=${{ secrets.R2_BUCKET_NAME }}" >> backend/.env
          echo "R2_ACCOUNT_ID=${{ secrets.R2_ACCOUNT_ID }}" >> backend/.env
          echo "PORT=${{ secrets.PORT }}" >> backend/.env

      - name: Build and Push Docker images
        run: |
          # Build and push the backend image
          docker build -t cnhjp/file-manager-backend:latest -f backend/Dockerfile backend/
          docker push cnhjp/file-manager-backend:latest

          # Build and push the frontend image
          docker build -t cnhjp/file-manager-frontend:latest -f frontend/Dockerfile frontend/
          docker push cnhjp/file-manager-frontend:latest

      - name: Deploy to Server
        run: |
          echo "${{ secrets.TCT_SSH_PRIVATE_KEY }}" > id_rsa
          chmod 600 id_rsa
          eval "$(ssh-agent -s)"
          ssh-add id_rsa
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.TCT_SSH_PORT }} root@${{ secrets.TCT_SSH_IP }} "
            docker stop file-manager-frontend || true && \
            docker rm file-manager-frontend || true && \
            docker stop file-manager-backend || true && \
            docker rm file-manager-backend || true && \
            docker image rm cnhjp/file-manager-backend || true && \
            docker image rm cnhjp/file-manager-frontend || true && \
            docker pull cnhjp/file-manager-backend && \
            docker pull cnhjp/file-manager-frontend && \
            docker run -d --name file-manager-frontend -p 8081:80 cnhjp/file-manager-frontend && \
            docker run -d --name file-manager-backend -p 3838:3838 cnhjp/file-manager-backend"
